runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  MONGO_URI: "mongodb+srv://highhari:harilovesmongo@ciclecluster.1t5nbzl.mongodb.net/?retryWrites=true&w=majority&tls=true&appName=CicleCluster"

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.10" 